"""create stock observations

Revision ID: 643954515d3a
Revises: 4d278618dcc7
Create Date: 2026-08-31 12:38:37.353076

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "643954515d3a"
down_revision: str | Sequence[str] | None = "4d278618dcc7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("camera_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("detected_units", sa.Integer(), nullable=False),
        sa.Column("shelf_capacity", sa.Integer(), nullable=False),
        sa.Column("stock_percentage", sa.Float(), nullable=False),
        sa.Column("detector_name", sa.String(length=50), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "detected_units >= 0", name="ck_stock_observations_detected_units_non_negative"
        ),
        sa.CheckConstraint(
            "shelf_capacity > 0", name="ck_stock_observations_shelf_capacity_positive"
        ),
        sa.CheckConstraint(
            "stock_percentage >= 0 AND stock_percentage <= 100",
            name="ck_stock_observations_percentage_range",
        ),
        sa.ForeignKeyConstraint(["camera_id"], ["cameras.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_observations_camera_id"), "stock_observations", ["camera_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_observations_captured_at"),
        "stock_observations",
        ["captured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_observations_product_id"), "stock_observations", ["product_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_observations_product_id"), table_name="stock_observations")
    op.drop_index(op.f("ix_stock_observations_captured_at"), table_name="stock_observations")
    op.drop_index(op.f("ix_stock_observations_camera_id"), table_name="stock_observations")
    op.drop_table("stock_observations")
    # ### end Alembic commands ###
