"""add shelf configurations

Revision ID: 788b47208805
Revises: 643954515d3a
Create Date: 2026-08-31 15:19:15.177200

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "788b47208805"
down_revision: str | Sequence[str] | None = "643954515d3a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shelf_configurations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("camera_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("detector_type", sa.String(length=50), nullable=False),
        sa.Column("reference_image_path", sa.String(length=500), nullable=True),
        sa.Column("detector_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["camera_id"], ["cameras.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "camera_id", "product_id", name="uq_shelf_configurations_camera_product"
        ),
    )
    op.create_index(
        op.f("ix_shelf_configurations_camera_id"),
        "shelf_configurations",
        ["camera_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shelf_configurations_product_id"),
        "shelf_configurations",
        ["product_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shelf_configurations_product_id"), table_name="shelf_configurations")
    op.drop_index(op.f("ix_shelf_configurations_camera_id"), table_name="shelf_configurations")
    op.drop_table("shelf_configurations")
    # ### end Alembic commands ###
