"""add stock alerts and low stock threshold

Revision ID: be08fbffcc91
Revises: 788b47208805
Create Date: 2026-09-01 16:43:08.857364

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be08fbffcc91"
down_revision: str | Sequence[str] | None = "788b47208805"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_alerts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stock_observation_id", sa.UUID(), nullable=False),
        sa.Column("stock_percentage", sa.Float(), nullable=False),
        sa.Column("threshold_percentage", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "stock_percentage >= 0 AND stock_percentage <= 100",
            name="ck_stock_alerts_stock_percentage",
        ),
        sa.CheckConstraint(
            "threshold_percentage >= 0 AND threshold_percentage <= 100",
            name="ck_stock_alerts_threshold_percentage",
        ),
        sa.ForeignKeyConstraint(
            ["stock_observation_id"], ["stock_observations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_alerts_stock_observation_id"),
        "stock_alerts",
        ["stock_observation_id"],
        unique=True,
    )
    op.add_column(
        "shelf_configurations",
        sa.Column("low_stock_threshold", sa.Float(), server_default="50", nullable=False),
    )
    op.create_check_constraint(
        "ck_shelf_configurations_low_stock_threshold",
        "shelf_configurations",
        "low_stock_threshold >= 0 AND low_stock_threshold <= 100",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_shelf_configurations_low_stock_threshold", "shelf_configurations", type_="check"
    )
    op.drop_column("shelf_configurations", "low_stock_threshold")
    op.drop_index(op.f("ix_stock_alerts_stock_observation_id"), table_name="stock_alerts")
    op.drop_table("stock_alerts")
    # ### end Alembic commands ###
