"""initial database setup

Revision ID: cd3622f80869
Revises:
Create Date: 2026-08-28 13:31:03.912092

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "cd3622f80869"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
